ifeq ($(config),debug)
  TARGET_DIR = Debug
else
  TARGET_DIR = Release
endif

.PHONY: run build gen snake snake-run tetris tetris-run editor-run

build: $(PROJECTS)

# Friendly aliases for the separate Snake game executable.
# Usage:
#   make snake              # build snakegame
#   make snake-run          # build + run snakegame
#   make snake run          # also works: builds snake, then runs snakegame
snake: snakegame

run: snake-run

snake-run: snake
	@echo "[make] Running snakegame ($(config))"
	./bin/$(TARGET_DIR)/snakegame/snakegame

# Friendly aliases for the separate Tetris game executable.
# Usage:
#   make tetris            # build tetrisgame
#   make tetris-run        # build + run tetrisgame
tetris: tetrisgame

tetris-run: tetris
	@echo "[make] Running tetrisgame ($(config))"
	./bin/$(TARGET_DIR)/tetrisgame/tetrisgame

editor-run: eclipseeditor
	@echo "[make] Running eclipseeditor ($(config))"
	./bin/$(TARGET_DIR)/eclipseeditor/eclipseeditor

gen:
	@echo "Generating project files..."
	./premake.sh gen
